### ISSUE TITLE
Support For Henry Grattan

### ISSUE THREAD

**Issue by theycallmemac** [Frazl/DCU-Labs-RestAPI#1]
Good going on this!!

Support for other building such as the Henry Grattan Building and the Business Building would be nice.

Something like this API could act as a workaround for DCU's current timetable API. It would certainly be much more reliable, it could even improve the the reliability of my [dcurooms](https://github.com/theycallmemac/dcurooms) command line tool.

I'll delve a little more into your code here when I get a chance. I may try build this in if I get a chance too.

**Comment by Frazl** [comment]
What do you mean DCU's current timetable API? Do they have one? 

Support for those building would be simple if you can supply the room codes. I presume they're in dcurooms so will have a quick look around that and see what I can do.

**Comment by Frazl** [comment]
@theycallmemac  The latest version now allows for checking the following rooms. 

`'CG01', 'CG02', 'CG03', 'CG04', 'CG05', 'CG06', 'CG11', 'CG12', 'CG20', 'CG68', 'CG86', 'C166'`

**Comment by theycallmemac** [comment]
That's great to hear! I'll start working on integrating this into dcurooms over the christmas period !
